services:
  mongodb:
    image: mongo:latest
    container_name: penny-coop-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: penny-coop-redis
    ports:
      - '6379:6379'

volumes:
  mongodb_data:
